const createTypography = (
  fontSize,
  fontWeight,
  color,
  contrastText,
  textTransform = "none"
) => ({
  fontSize,
  fontWeight,
  color,
  contrastText,
  textTransform,
});

export const typography = {
  fontFamily: '"Roboto", "Helvetica", "Arial", sans-serif',
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  h1: createTypography("2rem", 700, "inherit", "inherit"),
  h2: createTypography("1.5rem", 500, "inherit", "inherit"),
  h3: createTypography("1.2rem", 400, "inherit", "inherit"),
  h4: createTypography("1rem", 400, "inherit", "inherit"),
  h5: createTypography("0.875rem", 400, "inherit", "inherit"),
  h6: createTypography("0.75rem", 300, "inherit", "inherit"),
  subtitle1: createTypography("1rem", 400, "inherit", "inherit"),
  subtitle2: createTypography("0.875rem", 400, "inherit", "inherit"),
  body1: createTypography("1rem", 400, "inherit", "inherit"),
  body2: createTypography("0.875rem", 400, "inherit", "inherit"),
  button: createTypography("0.875rem", 500, "inherit", "inherit", "uppercase"),
  caption: createTypography("0.75rem", 400, "inherit", "inherit"),
  overline: createTypography("0.75rem", 400, "inherit", null, "uppercase"),
  link: createTypography("1rem", 400, "inherit", "inherit"),
  tooltip: createTypography("0.75rem", 300, "inherit", "inherit"),
  alert: createTypography("1rem", 500, "inherit", "inherit"),
  badge: createTypography("0.75rem", 700, "inherit", "inherit", "uppercase"),
  listItem: createTypography("1rem", 400, "inherit", "inherit"),
  menu: createTypography("1rem", 400, "inherit", "inherit"),
  dropdown: createTypography("1rem", 400, "inherit", "inherit"),
  tab: createTypography("1rem", 500, "inherit", "inherit"),
  modal: createTypography("1rem", 400, "inherit", "inherit"),
};
